### ISSUE TITLE
Add FreeSurfer LUT

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/containers#5]
A valid `FREESURFER_HOME` envvar and `FreeSurferColorLUT.txt` file are necessary for a couple of scripts. Don't particularly want to be downloading a 4GB FreeSurfer tarball within the recipe only to extract one text file and throw out the rest; but conversely not sure about just hosting a duplicate copy of a file from some other software.

**Comment by kaczmarj** [comment]
FreeSurferColorLUT.txt can be found on freesurfer's github page: https://github.com/freesurfer/freesurfer/blob/dev/distribution/FreeSurferColorLUT.txt

I'd recommend downloading from a permalink, for example https://raw.githubusercontent.com/freesurfer/freesurfer/4d5cc2f53cc6d53a2f2f71396673e5ca89482ae0/distribution/FreeSurferColorLUT.txt

**Comment by Lestropie** [comment]
Cheers @kaczmarj, was under the impression that code availability was still only via download for some reason...
